### ISSUE TITLE
Application Logo

### ISSUE THREAD

**Issue by cmwylie19** [cmwylie19/grpc-vs-rest#2]
**Is your feature request related to a problem? Please describe.**
Create a logo for the application.

**Describe the solution you'd like**
A logo with a transparent background in the following sizes:
- 512x512
- 192x192
- 64x64

**Describe alternatives you've considered**
Purchasing one or doing one myself

**Additional context**

**Comment by tomjsalter** [comment]
Hi @cmwylie19 I can help with this. 
Could you let me know if you have any preference to colours, iconography, name included (or not?), etc.

**Comment by cmwylie19** [comment]
Hi @tomjsalter, anything goes, you have complete control, just as long as the image's background is transparent, it is in PNG format.

Make sure you export the image to:
- 512x512
- 192x192
-  64x64

**Comment by cmwylie19** [comment]
> Hi @cmwylie19 I can help with this. Could you let me know if you have any preference to colours, iconography, name included (or not?), etc.

@tomjsalter,

Would you be able to do a wireframe mockup? Just one view, the wireframe will be implemented in [Material-ui](https://mui.com). 

The app has just one view, on that view, you click a button and the corresponding requests occur. There is info regarding the time it took for the requests to complete and images signifying the contents of the request that populate images. Mobile friendly. 

In terms of colors, icons, etc.- you have complete creative control. This project is really just for fun.  

Here is the link to the issue just incase you are interested. https://github.com/cmwylie19/grpc-vs-rest/issues/4
